#!/usr/bin/env sh
node_gyp_script="/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js"
if test -f "$node_gyp_script"; then
  node "$node_gyp_script" "$@"
else
  echo "Could not locate node-gyp. If building on Mac, install it globally by running: npm i -g node-gyp"
  if [ "x$npm_config_node_gyp" = "x" ]; then
    node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
  else
    "$npm_config_node_gyp" "$@"
  fi
fi
